# Configuración para el Helm Chart de Bitnami MySQL
image:
  registry: docker.io
  repository: bitnamilegacy/mysql
  tag: "8.0.35-debian-11-r0"

auth:
  database: petclinic
  rootPassword: petclinic

primary:
  persistence:
    enabled: false