alertmanager:
  enabled: false

prometheus-pushgateway:
  enabled: false

server:
  persistentVolume:
    enabled: false

  retention: 2h

  service:
    type: NodePort
    nodePort: 30090

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi