apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: spring-petclinic
  labels:
    app: api-gateway
  annotations:
    instrumentation.opentelemetry.io/inject-java: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: localhost:5000/api-gateway:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/liveness
          initialDelaySeconds: 90
          periodSeconds: 5
        readinessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/readiness
          initialDelaySeconds: 15
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 10"]
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: default
        volumeMounts:
        - name: config-volume
          mountPath: /application/config
      volumes:
      - name: config-volume
        configMap:
          name: api-gateway-config