apiVersion: v1
kind: ConfigMap
metadata:
  name: customers-service-config
  namespace: spring-petclinic
  labels:
    app: customers-service
data:
  application.yml: |
    server:
      port: 8080
      shutdown: graceful

    spring:
      jpa:
        open-in-view: false
        hibernate:
          ddl-auto: none

    management:
      security:
        enabled: false
      endpoints:
        web:
          exposure:
            include: "*"
      endpoint:
        health:
          show-details: always
    
    logging:
      level:
        org:
          springframework: INFO

    ---
    spring:
      config:
        activate:
          on-profile: mysql
      sql:
        init:
          schema-locations: classpath*:db/mysql/schema.sql
          data-locations: classpath*:db/mysql/data.sql
          mode: ALWAYS